install.packages('devtools')
install.packages('BiocManager')
devtools::install_github("End-to-end-provenance/provParseR")
devtools::install_github("End-to-end-provenance/provViz")
devtools::install_github("End-to-end-provenance/provSummarizeR")
devtools::install_github("End-to-end-provenance/rdtLite")
BiocManager::install(c('CodeDepends', 'lintr', 'rjson', 'Rgraphviz'), update= F)
devtools::install_github("MKLau/Rclean")
