"""add report column

Revision ID: de100889fcae
Revises: 8e74a347df9a
Create Date: 2020-05-06 11:12:28.922401

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'de100889fcae'
down_revision = '8e74a347df9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('report', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'report')
    # ### end Alembic commands ###
